sync:
  host_group: "UniFi"
  host_groups:
    uap: "UniFi AP"
    usw: "UniFi Switch"
    gateway: "UniFi Gateway"
    default: "UniFi"
  delete_missing: true
  templates:
    uap: "Generic by SNMP"
    usw: "Generic by SNMP"
    gateway: "Template Net ICMP Ping"
    default: "Template Net ICMP Ping"
